### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [devgianlu/DNSHero#1]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Arslan Şahin
Graphics Designer

**Comment by devgianlu** [comment]
Thank you very much for your time, but this app is using the assets from
zone.vision. Anyway we can keep in touch.

**Comment by devgianlu** [comment]
Thank you very much for your time, but this app is using the assets from [zone.vision](http://zone.vision). Anyway we can keep in touch.
