### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by fazlerabbi37** [devgianlu/DNSHero#10]
please consider adding a changelog file as make it easier for the uses to see that change.

**Comment by devgianlu** [comment]
This is going to happen from [v1.5.0](https://github.com/devgianlu/DNSHero/releases/tag/v1.5.0), changelog is [here](https://github.com/devgianlu/DNSHero/blob/master/CHANGELOG.md).

**Comment by fazlerabbi37** [comment]
awesome :smile:
