### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [devgianlu/DNSHero#2]
Hi,

What is the license of this project? If you haven't already decided, I would suggest GNU GPL v3.

This way we could add your app to [F-Droid](https://f-droid.org/) if you're ok 👍

**Comment by Poussinou** [comment]
Thanks 👍 

I see you're using `com.google.gms.google-services` which is obviously non-free. Would it be possible to write a new build flavor for f-droid without this?

Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/681) on our side

**Comment by devgianlu** [comment]
I'll see what can I do about that.

**Comment by IzzySoft** [comment]
While on it: using tags would be really helpful for the F-Droid Maintainers.

**Comment by devgianlu** [comment]
I'll put a tag for the two flavors once I've added the non-Google version.

**Comment by IzzySoft** [comment]
Cool. F-Droid can deal well with suffixes, so e.g. a tag pattern like `v1.2.3-foss` should work well.

**Comment by devgianlu** [comment]
Just added the `v1.0.5` tag. I've tried my best to remove all the non-foss dependencies and repositories from the Gradle build; I hope it's enough.

**Comment by IzzySoft** [comment]
Great, thanks! Can you also check for the insecure gradle [reported by the F-Droid bot](https://gitlab.com/fdroid/rfp/issues/681)?

**Comment by devgianlu** [comment]
Fixed with 89a54fcaa727d3c95f513bb68213d70a325818d7

**Comment by IzzySoft** [comment]
Cool! Then let the :robot: come and check again :laughing: I've already told it to rescan.

Oh, btw: Is that really your donation URL mentioned "over there"? After all, could be some imposter pretending to be you. I didn't see the donation URL mentioned here in the `README.md`. Might be a good idea to add it there as well (if it is really yours). I'd then add it to the metadata template I just included with the initial post at F-Droid.

**Comment by devgianlu** [comment]
I confirm it's me, but anyway I've updated my README.

**Comment by devgianlu** [comment]
Some apparently downloaded the app from F-Droid, but I can't find it. Can someone provide a link to it?

**Comment by Poussinou** [comment]
[Here](https://f-droid.org/packages/com.gianlu.dnshero/) you go. Thanks for your work and your cooperation !
