### ISSUE TITLE
Idea - Having a list of predefined checks for domains

### ISSUE THREAD

**Issue by wioxjk** [devgianlu/DNSHero#34]
Hi!
I have been using DNS Hero for quite some time and I like it!
Something that I have realized that I personally would like to se is the option to enable to more check, for example predefined SRV records for certain services (like matrix, minecraft and so on).

Those check should maybe be manually enabled in DNS Hero and not resolve it by default.

Let me know if I am unclear :)

**Comment by devgianlu** [comment]
Hi,
This app is based entirely on https://zone.vision and therefore supports only those features.
