### ISSUE TITLE
Can't build 1.1.0-foss

### ISSUE THREAD

**Issue by Rudloff** [devgianlu/DNSHero#4]
Hello,

I'm getting this error when trying to build 1.1.0-foss with https://github.com/devgianlu/CommonUtils/commit/9d9f1ba97fbe6fdcf98fd2462f0471a72033f2d8 and https://github.com/devgianlu/MaterialPreferences/commit/23068a4659a070ddb1d5a407d8490da902ea77e5:
```
A problem occurred evaluating project ':MaterialPreferences'.
> Plugin with id 'com.novoda.bintray-release' not found.
```

**Comment by devgianlu** [comment]
Oh sorry, I will sort this out soon.

**Comment by devgianlu** [comment]
I've fixed the issue. I used some git submodules, I hope it isn't a problem.

**Comment by Rudloff** [comment]
It builds correctly now, thanks!
(And the F-Droid build system supports submodules so it is way more convenient than having to get the dependencies manually :+1: )

Would it be possible to publish a new release with these fixes so we can package it?
